[package]
name = "crony-base-gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aws-config = { version = "=1.8.1", default-features = false, features = ["rt-tokio", "default-https-client"] }
aws-sdk-kms = { version = "=1.93.0", default-features = false, features = ["rt-tokio", "default-https-client"] }
aws-sdk-sts = { version = "=1.91.0", default-features = false, features = ["rt-tokio", "default-https-client"] }
axum.workspace = true
crony-audit = { path = "../crony-audit" }
crony-base = { path = "../crony-base", features = ["aws-kms", "gateway-service"] }
crony-store = { path = "../crony-store" }
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
alloy = { version = "=1.8.3", default-features = false, features = ["signer-local"] }
aws-smithy-http-client = { version = "=1.1.13", default-features = false, features = ["test-util"] }
aws-smithy-types = "=1.5.0"
base64.workspace = true
k256 = { version = "0.13", default-features = false, features = ["pkcs8"] }
